Repository schubergphilis/terraform-aws-mcaf-aurora, pull requests merged in 2023-07, with the labels that each got.

#46 docs: add upgrade steps to v3.0.0
  UPGRADING.md
Labels: documentation, no-changelog

#47 security: set cluster parameter `require_secure_transport` to ON by default and set apply methods
  README.md
  variables.tf
Labels: enhancement, security

#44 feature: Adds custom_endpoints output
  README.md
  outputs.tf
Labels: feature

#43 bug(entrypoint): Depend on cluster instances to exist
  main.tf
Labels: bug
